services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1
      - MYSQL_DATABASE=datamine_synergy
      - MYSQL_USER=datamine_user
      - MYSQL_PASSWORD=datamine_password
      - MYSQL_HOST=db
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb:10.6.16
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=datamine_synergy
      - MYSQL_USER=datamine_user
      - MYSQL_PASSWORD=datamine_password
    ports:
      - "3306:3306"
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --skip-character-set-client-handshake
      --default-authentication-plugin=mysql_native_password
      --bind-address=0.0.0.0
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "datamine_user", "-pdatamine_password"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mariadb_data: 